name: Spec
description: Approved implementation plan ready for execution
type: Spec
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: One paragraph summary of the specification
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Draft
        - Review
        - Approved
        - In Progress
        - Complete
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: 'Problem Statement: Current State'
      placeholder: What exists today?
    validations:
      required: true

  - type: textarea
    id: desired-state
    attributes:
      label: 'Problem Statement: Desired State'
      placeholder: What should exist?
    validations:
      required: true

  - type: textarea
    id: why-now
    attributes:
      label: 'Problem Statement: Why Now?'
      placeholder: Why is this the right time?

  - type: textarea
    id: approach
    attributes:
      label: 'Proposed Solution: Approach'
      placeholder: High-level description of the solution
    validations:
      required: true

  - type: checkboxes
    id: components
    attributes:
      label: Components Affected
      options:
        - label: Pages (`/src/app/`)
        - label: Components (`/src/components/`)
        - label: API Routes (`/src/app/api/`)
        - label: Hooks (`/src/hooks/`)
        - label: Utilities (`/src/lib/`)
        - label: Middleware (`/src/middleware.ts`)
        - label: Styles/Theming (Tailwind, Flowbite)
        - label: Tests (`/__tests__/`)
        - label: CI/CD (`.github/workflows/`)
        - label: Infrastructure (`/cloudformation/`)

  - type: textarea
    id: key-changes
    attributes:
      label: Key Changes
      render: text
      placeholder: Describe key code changes, new files, or architectural changes

  - type: textarea
    id: api-changes
    attributes:
      label: API Changes
      render: typescript
      placeholder: |
        // New API routes or changes to existing ones
        POST /api/endpoint
        Request: { }
        Response: { }

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Plan
      placeholder: |
        - [ ] **Phase 1:**
        - [ ] **Phase 2:**
        - [ ] **Phase 3:**

        **Dependencies:**

        **Migration strategy:**
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: Testing
      placeholder: |
        - [ ] Unit tests
        - [ ] Component tests
        - [ ] Manual verification

  - type: textarea
    id: rollout
    attributes:
      label: Rollout
      placeholder: |
        **Environments:** Development → Staging → Production
        **Feature flags:**
        **Rollback plan:**

  - type: textarea
    id: success
    attributes:
      label: Success Criteria
      placeholder: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true

  - type: textarea
    id: questions
    attributes:
      label: Open Questions
      placeholder: |
        - [ ]

  - type: textarea
    id: references
    attributes:
      label: References
      placeholder: |
        - Related: #
        - Docs:
