name: 'Check Runner Availability'
description: 'Check if self-hosted GitHub Actions runners are available and set outputs for conditional runner selection. Supports both organization and repository-level runners for fork compatibility.'

inputs:
  runner_labels:
    description: 'Comma-separated list of required runner labels (e.g., "self-hosted,Linux,X64")'
    required: false
    default: 'self-hosted,Linux,X64'
  runner_scope:
    description: 'Where to check for runners: "org" (organization), "repo" (repository), or "both" (check repo first, fallback to org)'
    required: false
    default: 'both'
  github_token:
    description: 'GitHub token for API access (needs admin:org for org runners, or repo scope for repo runners)'
    required: true

outputs:
  runners_available:
    description: 'Whether self-hosted runners are available (true/false)'
    value: ${{ steps.check-runners.outputs.runners_available }}
  runner_type:
    description: 'Recommended runner type (self-hosted or github-hosted)'
    value: ${{ steps.check-runners.outputs.runner_type }}
  runner_config:
    description: 'JSON array of runner configuration to use'
    value: ${{ steps.check-runners.outputs.runner_config }}

runs:
  using: 'composite'
  steps:
    - name: Check if self-hosted runners are available
      id: check-runners
      shell: bash
      run: |
        RUNNER_LABELS="${{ inputs.runner_labels }}"
        RUNNER_SCOPE="${{ inputs.runner_scope }}"

        # Validate runner_scope input
        if [[ ! "$RUNNER_SCOPE" =~ ^(org|repo|both)$ ]]; then
          echo "⚠️ Invalid runner_scope: $RUNNER_SCOPE. Using default: both"
          RUNNER_SCOPE="both"
        fi

        # If no labels or "github-hosted", use GitHub-hosted runners (skip API check)
        if [ -z "$RUNNER_LABELS" ] || [ "$RUNNER_LABELS" = "github-hosted" ]; then
          echo "✅ Using GitHub-hosted runners (ubuntu-latest)"
          echo ""
          echo "runners_available=false" >> $GITHUB_OUTPUT
          echo "runner_type=github-hosted" >> $GITHUB_OUTPUT
          {
            echo 'runner_config<<EOF'
            echo '["ubuntu-latest"]'
            echo 'EOF'
          } >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "🔍 Checking if self-hosted GitHub Actions runners are available..."
        echo "Repository: ${{ github.repository }}"
        echo "Required labels: ${RUNNER_LABELS}"
        echo "Runner scope: ${RUNNER_SCOPE}"
        echo ""

        # Convert comma-separated labels to array
        IFS=',' read -ra REQUIRED_LABELS <<< "${RUNNER_LABELS}"

        # Build the runner_config JSON array from the input labels
        RUNNER_CONFIG_JSON=$(printf '%s\n' "${REQUIRED_LABELS[@]}" | jq -R . | jq -s . 2>/dev/null)
        if [ -z "$RUNNER_CONFIG_JSON" ] || [ "$RUNNER_CONFIG_JSON" = "null" ]; then
          echo "⚠️ Failed to build runner config JSON, using fallback"
          RUNNER_CONFIG_JSON='["ubuntu-latest"]'
        fi

        # Extract org and repo from repository name
        ORG_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f1)
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)

        # Function to check runners from a given API endpoint
        check_runners_at_endpoint() {
          local endpoint="$1"
          local scope_name="$2"

          echo "📡 Checking ${scope_name} runners: ${endpoint}"
          local response=$(curl -s -w "HTTP_CODE:%{http_code}" -H "Authorization: token ${{ inputs.github_token }}" "${endpoint}")

          local http_code=$(echo "$response" | grep -o "HTTP_CODE:[0-9]*" | cut -d: -f2)
          response=$(echo "$response" | sed 's/HTTP_CODE:[0-9]*$//')

          if [ "$http_code" != "200" ]; then
            echo "  ⚠️ ${scope_name} API returned status ${http_code} (may not have permission or no runners configured)"
            echo ""
            return 1
          fi

          if ! echo "$response" | jq . >/dev/null 2>&1; then
            echo "  ⚠️ Invalid JSON response from ${scope_name} API"
            echo "  Response preview: $(echo "$response" | head -c 200)"
            return 1
          fi

          # Check for matching online runners
          local matching=$(echo "$response" | jq -r --argjson required_labels "$(printf '%s\n' "${REQUIRED_LABELS[@]}" | jq -R . | jq -s .)" '
            .runners[] |
            select(.status == "online") |
            select(.labels | map(.name) | sort as $runner_labels |
                   $required_labels | all(. as $req | $runner_labels | index($req))) |
            .name
          ' 2>/dev/null || echo "")

          local count=$(echo "$matching" | grep -v '^$' | wc -l | tr -d ' ')

          if [ "$count" -gt 0 ]; then
            echo "  ✅ Found $count online runner(s) in ${scope_name}:"
            echo "$matching" | while IFS= read -r runner; do
              [ -n "$runner" ] && echo "    - $runner"
            done
            return 0
          else
            echo "  ℹ️ No matching online runners in ${scope_name}"
            # Show what's available for debugging
            local all_runners=$(echo "$response" | jq -r '.runners[] | "    - \(.name): \(.status)"' 2>/dev/null || echo "    (none)")
            if [ -n "$all_runners" ] && [ "$all_runners" != "    (none)" ]; then
              echo "  Available runners:"
              echo "$all_runners"
            fi
            return 1
          fi
        }

        FOUND_RUNNERS=false

        # Check based on scope setting
        case "${RUNNER_SCOPE}" in
          repo)
            echo "🔍 Checking repository-level runners only..."
            if check_runners_at_endpoint "https://api.github.com/repos/${{ github.repository }}/actions/runners" "repository"; then
              FOUND_RUNNERS=true
            fi
            ;;
          org)
            echo "🔍 Checking organization-level runners only..."
            if check_runners_at_endpoint "https://api.github.com/orgs/${ORG_NAME}/actions/runners" "organization"; then
              FOUND_RUNNERS=true
            fi
            ;;
          both)
            echo "🔍 Checking repository-level runners first, then organization..."
            echo ""
            if check_runners_at_endpoint "https://api.github.com/repos/${{ github.repository }}/actions/runners" "repository"; then
              FOUND_RUNNERS=true
            elif check_runners_at_endpoint "https://api.github.com/orgs/${ORG_NAME}/actions/runners" "organization"; then
              FOUND_RUNNERS=true
            fi
            ;;
        esac

        echo ""

        if [ "$FOUND_RUNNERS" = true ]; then
          echo "✅ Self-hosted runners are available and ready!"
          echo ""

          # Set outputs for available runners using heredoc for safe multiline handling
          echo "runners_available=true" >> $GITHUB_OUTPUT
          echo "runner_type=self-hosted" >> $GITHUB_OUTPUT
          {
            echo 'runner_config<<EOF'
            echo "${RUNNER_CONFIG_JSON}"
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        else
          echo "⚠️ No suitable self-hosted runners available"
          echo "🔄 Falling back to GitHub-hosted runners (ubuntu-latest)"
          echo ""
          echo "💡 To use self-hosted runners:"
          echo "   - For forks: Add a self-hosted runner to your repository"
          echo "   - Labels needed: ${RUNNER_LABELS}"
          echo ""

          # Set outputs for fallback to GitHub-hosted runners using heredoc
          echo "runners_available=false" >> $GITHUB_OUTPUT
          echo "runner_type=github-hosted" >> $GITHUB_OUTPUT
          {
            echo 'runner_config<<EOF'
            echo '["ubuntu-latest"]'
            echo 'EOF'
          } >> $GITHUB_OUTPUT
        fi
